version: '3'
services:
  web:
    build: ./app
    container_name: myWeb
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - my_network
  redis:
    build: ./redis
    container_name: myRedis
    ports:
      - "6379:6379"
    networks:
      - my_network
networks:
  my_network: